n = input('Escreva algo:')
print(f'isso é maisculo? {n.isupper()}')
print(f'Está em minúsculo? {n.islower()}')
print(f'é um alfanumérico? {n.isalnum()}')
print(f'tipo primitivo desse valor {type(n)}')